### ISSUE TITLE
Error loading script server.lua

### ISSUE THREAD

**Issue by Sina30** [Sukrayt/Sukra_Moneywash#1]
[script:Sukra_Moneywa] Error loading script server.lua in resource Sukra_Moneywash: @Sukra_Moneywash/server.lua:110: attempt to index a nil value (global 'ESX')
[script:Sukra_Moneywa] stack traceback:
[script:Sukra_Moneywa] 	@Sukra_Moneywash/server.lua:110: in main chunk

**Comment by Sukrayt** [comment]
Which Esx Version are you using?

> [script:Sukra_Moneywa] Error loading script server.lua in resource Sukra_Moneywash: @Sukra_Moneywash/server.lua:110: attempt to index a nil value (global 'ESX') [script:Sukra_Moneywa] stack traceback: [script:Sukra_Moneywa] @Sukra_Moneywash/server.lua:110: in main chunk

**Comment by Sukrayt** [comment]
should be fixed now, download the newest release

> [script:Sukra_Moneywa] Error loading script server.lua in resource Sukra_Moneywash: @Sukra_Moneywash/server.lua:110: attempt to index a nil value (global 'ESX') [script:Sukra_Moneywa] stack traceback: [script:Sukra_Moneywa] @Sukra_Moneywash/server.lua:110: in main chunk

**Comment by Sina30** [comment]
I use esx 1.2

**Comment by Sina30** [comment]
now i get the error

[  script:es_extended] [WARNING] Server-Callback "sukra:moneywash:getmoneyy" existiert nicht. Stellen Sie sicher, dass die serverseitige Datei wirklich geladen wird. Ein Fehler in dieser Datei kann dazu führen, dass sie nicht geladen wird.

**Comment by Sukrayt** [comment]
did you modify the script?

**Comment by Sina30** [comment]
No, I loaded it from you as it is

**Comment by Sukrayt** [comment]
hm weird please join my discord so we can fix this together I need to look into this deeper
https://discord.gg/yWAHqkgURB
